---

- name: Launching an EC2 machine
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: Launching EC2
      ec2:     
        key_name: Mac
        region: "{{ REGION }}"
        instance_type: "{{ EC2_TYPE }}"
        image: "{{ AMI_ID }}"
        wait: yes
        count: "{{ COUNT }}" 
        vpc_subnet_id: "{{ SUBNET_ID }}"
        assign_public_ip: yes
