---

- name: Launching an EC2 machine
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: Get Subnet ID For AZ A
      amazon.aws.ec2_vpc_subnet_info:
   #  ec2_vpc_subnet_facts:
        region: "{{ REGION }}"
        filters:
        "tag:Name": "{{ ENVIRONMENT }}"
      register: ec2_subnet_a
    - name: Launching EC2
      ec2:     
        key_name: Mac
        region: "{{ REGION }}"
        instance_type: "{{ EC2_TYPE }}"
        image: "{{ AMI_ID }}"
        wait: yes
        count: "{{ COUNT }}" 
        vpc_subnet_id: "{{ ec2_subnet_a.subnets.0.id }}"
        assign_public_ip: yes
