---

- name: Create S3
  hosts: localhost
  become: true
  become_user: root
  gather_facts: no
  tasks:
    - name: Create S3
      s3_bucket:
        name: ahmadsohailisansiblepro
        state: present
      
